blog/urls.py
from django.conf.urls import url
from blog import views


app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<post_id>\d+)$', views.post, name='post'),

    url(r'^categories/$', views.categories, name='categories'),
    url(r'^category/(?P<category_name>\w+)', views.category, name='category'),

    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^dashboard/posts/(?P<post_status>\d+)',
        views.dashboard_my_posts,
        name='dashboard_my_posts_filtered'),
    url(r'^dashboard/posts/', views.dashboard_my_posts, name='dashboard_my_posts'),
    url(r'^dashboard/post/create/', views.dashboard_create_post, name='dashboard_create_post'),
]

blogger/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from users.views import login, logout

import django_pydenticon.urls


urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),

    url(r'^', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^identicon/', include(django_pydenticon.urls.get_patterns())),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import models


class Post(models.Model):
    PUBLISHED = 1
    DRAFT = 2
    ARCHIVED = 3

    STATUSES = (
        (PUBLISHED, 'Published'),
        (DRAFT, 'Draft'),
        (ARCHIVED, 'Archived'),
    )

    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='author')
    category = models.ManyToManyField('blog.Category')
    heading = models.CharField(max_length=50)
    body = models.TextField()
    cover = models.ImageField(upload_to='covers')
    status = models.SmallIntegerField(choices=STATUSES, default=DRAFT)
    comments = models.ManyToManyField('blog.Comment')

    date_modified = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Post - {}".format(self.heading)


class Category(models.Model):
    name = models.CharField(max_length=50)
    icon = models.ImageField(upload_to='icons')

    def __str__(self):
        return "Category - {}".format(self.name)

    def get_active_posts_with_category_count(self):
        return Post.objects.filter(category=self.id).count()


class Comment(models.Model):
    HIDDEN = 1
    VISIBLE = 2
    DELETED = 3

    STATUSES = (
        (HIDDEN, 'Hidden'),
        (VISIBLE, 'Visible'),
        (DELETED, 'Deleted'),
    )

    username = models.CharField(default='Anonymous', blank=True, max_length=50)
    body = models.TextField()
    status = models.SmallIntegerField(choices=STATUSES, default=HIDDEN)

    date_modified = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms

from blog.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        default_attributes = {
            'class': 'form-control'
        }

        model = Post
        fields = ('heading', 'body', 'cover', 'status', 'category', )
        exclude = ('user', )
        widgets = {
            'heading': forms.TextInput(attrs=default_attributes),
            'body': forms.Textarea(attrs=default_attributes),
            # 'cover': forms.FileInput(attrs=default_attributes),
            'status': forms.widgets.Select(attrs=default_attributes),
            'category': forms.widgets.SelectMultiple(attrs=default_attributes),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        default_attributes = {
            'class': 'form-control'
        }

        model = Comment
        fields = ('username', 'body', )
        widgets = {
            'username': forms.TextInput(attrs=default_attributes),
            'body': forms.Textarea(attrs=default_attributes),
        }

users/forms.py
from django import forms


class LoginForm(forms.Form):
    default_attributes = {
        'class': 'form-control'
    }

    username = forms.CharField(label='Username',
                               max_length=50,
                               widget=forms.TextInput(attrs=default_attributes), )
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput(attrs=default_attributes), )

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect

from .models import Post, Category
from .forms import PostForm, CommentForm


def index(request):
    posts = Post.objects.all()

    context = {
        'posts': posts
    }
    return render(request, 'blog/index.html', context)


def post(request, post_id):
    post_obj = get_object_or_404(Post, id=post_id)
    comments = post_obj.comments.all()
    comment_form = CommentForm()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_obj = comment_form.save()
            post_obj.comments.add(comment_obj)
            return redirect('blog:post', post_id=post_id)

    context = {
        'post': post_obj,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'blog/post.html', context)


def dashboard(request):
    user = request.user

    published_posts_count = Post.objects.filter(author=user, status=Post.PUBLISHED).count()
    draft_posts_count = Post.objects.filter(author=user, status=Post.DRAFT).count()
    archived_posts_count = Post.objects.filter(author=user, status=Post.ARCHIVED).count()

    context = {
        'published_posts_count': published_posts_count,
        'draft_posts_count': draft_posts_count,
        'archived_posts_count': archived_posts_count
    }

    return render(request, 'blog/dashboard.html', context)


def dashboard_my_posts(request, post_status=None):
    user = request.user

    qs_filter = {
        'author': user
    }

    if post_status is not None:
        qs_filter = {
            'author': user,
            'status': post_status
        }

    # All posts (unfiltered)
    user_posts = Post.objects.filter(**qs_filter)

    context = {
        'posts': user_posts
    }
    return render(request, 'blog/dashboard_my_posts.html', context)


def dashboard_create_post(request):
    success = False
    post_id = None
    user = request.user
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.author = user
            f.save()

            success = True
            post_id = f.id

    context = {
        'form': form,
        'success': success,
        'post_id': post_id
    }

    return render(request, 'blog/dashboard_create_post.html', context)


def categories(request):
    categories_list = Category.objects.all()

    context = {
        'categories': categories_list
    }
    return render(request, 'blog/category_list.html', context)


def category(request, category_name):
    category_obj = get_object_or_404(Category, name__iexact=category_name)
    posts = Post.objects.filter(category=category_obj)

    context = {
        'category': category_obj,
        'posts': posts,
    }

    return render(request, 'blog/posts_by_category.html', context)

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from .forms import LoginForm


def login(request):
    login_form = LoginForm()

    if request.method == 'POST':
        login_form = LoginForm(request.POST, request.FILES)
        if login_form.is_valid():
            data = request.POST
            user = authenticate(request, username=data['username'], password=data['password'])
            if user is not None:
                auth_login(request, user)
                return redirect('/')
            else:
                login_form.add_error(None, 'There are no users that match your credentials.')

    context = {
        'login_form': login_form
    }
    return render(request, 'users/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('login')

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Blogger</title>

    <link rel="stylesheet" type="text/css" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% include 'includes/main_header.html' %}

    <div class="row">
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    </div>

    <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/blog/category_list.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="container">
      <h1>Categories</h1>
      {% for category in categories %}
        <div class="well card">
          <div class="row">
            <div class="col-md-8">
              <h2><a href="{% url 'blog:category' category.name %}">{{ category.name }}</a></h2>
            </div>
            <div class="col-md-4">
              <h3>
                {{ category.get_active_posts_with_category_count }}
                &nbsp;<small>post{{ category.get_active_posts_with_category_count|pluralize }}</small></h3>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/blog/dashboard.html
{% extends "base.html" %}

{% block content %}

  <div class="row">
    <div class="col-md-4 ">
      <h1>Dashboard</h1>
      {% include 'includes/blog/dashboard_sidebar.html' %}
    </div>

    <div class="col-md-8">
      <h1>Stats</h1>
      <div class="row">
        <div class="col-md-4 ">
          <div class="dash-item text-center">
            <span class="item-name">Published Posts</span>
            <span class="item-count">{{ published_posts_count }}</span>
            <a href="{% url 'blog:dashboard_my_posts_filtered' 1 %}" class="btn btn-primary">View Posts</a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="dash-item text-center">
            <span class="item-name">Drafts</span>
            <span class="item-count">{{ draft_posts_count }}</span>
            <a href="{% url 'blog:dashboard_my_posts_filtered' 2 %}" class="btn btn-primary">View Posts</a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="dash-item text-center">
            <span class="item-name">Archived Posts</span>
            <span class="item-count">{{ archived_posts_count }}</span>
            <a href="{% url 'blog:dashboard_my_posts_filtered' 3 %}" class="btn btn-primary">View Posts</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/blog/dashboard_create_post.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-md-4 ">
      <h1>Dashboard</h1>
      {% include 'includes/blog/dashboard_sidebar.html' %}
    </div>
    <div class="col-md-8">
      <h1>Create Post</h1>
      {% if success and post_id %}
        <div class="alert alert-success">
          Post has been created! View it <a href="{% url 'blog:post' post_id %}">here</a>!
        </div>
      {% endif %}
      <form method="POST" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {% for error in form.non_field_errors %}
                    <p class="text-danger">{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <div class="form-group">
            <label for="{{ form.heading.id_for_label }}">Heading</label>
            {% if form.heading.errors %}
                {% for error in form.heading.errors %}
                    <p class="text-danger">
                        {{ error|escape }}
                    </p>
                {% endfor %}
            {% endif %}
            {{ form.heading }}
        </div>
        <div class="form-group">
            <label for="{{ form.body.id_for_label }}">Body</label>
            {% if form.body.errors %}
                {% for error in form.body.errors %}
                    <p class="text-danger">
                        {{ error|escape }}
                    </p>
                {% endfor %}
            {% endif %}
            {{ form.body }}
        </div>
        <div class="form-group">
            <label for="{{ form.cover.id_for_label }}">Cover</label>
            {% if form.cover.errors %}
                {% for error in form.cover.errors %}
                    <p class="text-danger">
                        {{ error|escape }}
                    </p>
                {% endfor %}
            {% endif %}
            {{ form.cover }}
        </div>
        <div class="form-group">
            <label for="{{ form.status.id_for_label }}">Status</label>
            {% if form.status.errors %}
                {% for error in form.status.errors %}
                    <p class="text-danger">
                        {{ error|escape }}
                    </p>
                {% endfor %}
            {% endif %}
            {{ form.status }}
        </div>
        <div class="form-group">
            <label for="{{ form.category.id_for_label }}">Categories</label>
            {% if form.category.errors %}
                {% for error in form.category.errors %}
                    <p class="text-danger">
                        {{ error|escape }}
                    </p>
                {% endfor %}
            {% endif %}
            {{ form.category }}
        </div>
        <div class="form-group">
          <button class="btn btn-primary">Create Post</button>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

templates/blog/dashboard_my_posts.html
{% extends "base.html" %}

{% block content %}

  <div class="row">
    <div class="col-md-4 ">
      <h1>Dashboard</h1>
      {% include 'includes/blog/dashboard_sidebar.html' %}
    </div>

    <div class="col-md-8">
      <h1>My Posts</h1>
      <div class="row">
        <div class="col-md-12">
            {% if posts %}
              {% for post in posts %}
                  <div class="well post-card">
                    <h2>{{ post.heading }}</h2>
                    <small>By: {{ post.author }}</small>
                    <p>
                        <span class="label label-default">{{ post.get_status_display }}</span>
                    </p>
                    <p>{{ post.body|truncatewords:10 }}</p>
                  </div>
              {% endfor %}
            {% else %}
              <div class="alert alert-warning">
                <p>There are no posts.</p>
              </div>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/blog/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Blog Index</h1>
{% endblock content %}

templates/blog/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Blog Index</h1>

  <div class="row">
    <div class="container">
      {% for post in posts %}
        <div class="well post-card">
          <h2>{{ post.heading }}</h2>
          <small>By: {{ post.author }}</small>
          <p>{{ post.body|truncatewords:10 }}</p>
          <a href="{% url 'blog:post' post.id %}" class="btn btn-default">Read More <i class="glyphicon glyphicon-chevron-right"></i></a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/blog/post.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ post.heading }}</h1>
  <h2>by {{ post.author }}</h2>
  <hr>
  <div class="row">
    <div class="container">
      {{ post.body }}
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="container comments">
      <h2>Post a comment!</h2>
      <form method="POST">

        {% csrf_token %}
        {{ comment_form.as_p }}

        <div class="form-group">
          <button class="btn btn-default" type="submit">Post comment!</button>
        </div>
      </form>
      <hr>
      <h2>Comments</h2>
      <div class="container">
        {% if comments %}
          {% for comment in comments %}
            <div class="row">
              <div class="comment-wrap container well">
                <div class="col-sm-2">
                  <img class='comment-avatar img-rounded img-responsive img-thumbnail' src="{% url 'django_pydenticon:image' comment.id %}">
                  <br>
                  <span>by: <em>{{ comment.username }}</em></span>
                </div>
                <div class="col-sm-10">
                  <span>Date: {{ comment.date_created }}</span>
                  <hr>
                  {{ comment.body }}
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <div class="row">
            <div class="alert alert-info">
              <p>There are no comments yet! Be the first one to post!</p>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/blog/posts_by_category.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1>Category: {{ category.name }}</h1>
      <div class="row">
        <div class="col-md-12">
          {% if posts %}
            {% for post in posts %}
              <div class="well post-card">
                <h2><a href="{% url 'blog:post' post.id %}">{{ post.heading }}</a></h2>
                <small>By: {{ post.author }}</small>
                <p>
                    <span class="label label-default">{{ post.get_status_display }}</span>
                </p>
                <p>{{ post.body|truncatewords:10 }}</p>
              </div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/includes/blog/dashboard_sidebar.html
<ul class="list-group">
  <li class="list-group-item"><a href="{% url 'blog:dashboard' %}"><i class="glyphicon glyphicon-home"></i>&nbsp;Dashboard</a></li>
  <li class="list-group-item"><a href="{% url 'blog:dashboard_my_posts' %}"><i class="glyphicon glyphicon-th-list"></i>&nbsp;My Posts</a></li>
  <li class="list-group-item"><a href="{% url 'blog:dashboard_create_post' %}"><i class="glyphicon glyphicon-plus"></i>&nbsp;Add Post</a></li>
  <li class="list-group-item"><i class="glyphicon glyphicon-user"></i> My Profile</li>
  <li class="list-group-item"><i class="glyphicon glyphicon-cog"></i> Settings</li>
</ul>

templates/includes/main_header.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'blog:index' %}">Blog Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'blog:categories' %}">Categories</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            {{ request.user.username }}&nbsp;<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Create Post</a></li>
            <li><a href="{% url 'blog:dashboard' %}">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </li>
        {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

templates/users/login.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="container">
            <div class="col-md-6">
                <form novalidate method="POST">
                    {% if login_form.non_field_errors %}
                        <div class="alert alert-danger">
                            {% for error in login_form.non_field_errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ login_form.username.id_for_label }}">Username</label>
                        {% if login_form.username.errors %}
                            {% for error in login_form.username.errors %}
                                <p class="text-danger">
                                    {{ error|escape }}
                                </p>
                            {% endfor %}
                        {% endif %}
                        {{ login_form.username }}
                    </div>
                    <div class="form-group">
                        <label for="{{ login_form.password.id_for_label }}">Password</label>
                        {% if login_form.password.errors %}
                            {% for error in login_form.password.errors %}
                                <p class="text-danger">
                                    {{ error|escape }}
                                </p>
                            {% endfor %}
                        {% endif %}
                        {{ login_form.password }}
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}